name: drupal-demo
recipe: drupal8
config:
  webroot: web
  php: '7.3'

services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
  database:
    creds:
      database: drupal
      username: drupal
      password: drupal

  # Mailhog service to catch all mail notifications sent from appserver.
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

tooling:
  node:
    service: appserver
  npm:
    service: appserver
